spring:
  threads:
    virtual:
      enabled: true
  devtools:
    restart:
      enabled: true
  datasource:
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./medium;Mode=MYSQL
  h2:
    console:
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090
